[package]
name = "libraw-sys"
version = "0.5.6"
edition = "2021"
license = "MIT"

build = "build.rs"

[dependencies]
libc = "0.2.123"

[build-dependencies]
bindgen = { version = "0.59.2", optional = true }
pkg-config = "0.3.25"
cc = { version = "1.0.73", optional = true }
vergen = "7.2.1"
git2 = "0.14.4"

[features]
clone = []
bindgen = ["dep:bindgen", "clone"]
build = ["dep:cc", "clone"]
copy = []
