[package]
name = "libraw-sys"
version = "0.4.0"
authors = ["Soham Sen <soham@aftershoot.com>"]
description = "FFI bindings to libraw"
homepage = "https://github.com/aftershootco/libraw-sys"
repository = "https://github.com/aftershootco/libraw-sys"
license = "MIT"
readme = "README.md"
keywords = ["libraw", "raw", "camera"]

build = "build.rs"

[dependencies]
libc = "0.2.123"
