[package]
name = "libraw-sys"
version = "0.2.1"
authors = ["Soham Sen <soham@aftershoot.com>", "David Cuddeback <david.cuddeback@gmail.com>"]
description = "FFI bindings to libraw"
homepage = "https://github.com/aftershootco/libraw-sys"
repository = "https://github.com/aftershootco/libraw-sys"
license = "MIT"
readme = "README.md"
keywords = ["libraw", "raw", "camera"]

build = "build.rs"
links = "raw"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
cc = { version = "1.0", features = ["parallel"] }
