[package]
name = "libraw-sys"
version = "0.5.0"
edition = "2021"
license = "MIT"

build = "build.rs"

[dependencies]
libc = "0.2.123"

[build-dependencies]
bindgen = { version = "0.59.2", optional = true }
cc = { version = "1.0.73", optional = true }

[features]
bindgen = ["dep:bindgen"]
build = ["dep:cc"]
